"use client";
import {useEffect,useState} from "react";
import {AppShell} from "@/components/AppShell";import {Header} from "@/components/Header";import {Modal} from "@/components/Modal";import {supabase} from "@/lib/supabase";import {Trash2,Plus,Search,PackageOpen} from "lucide-react";
export default function Inventaris(){
 const [rows,setRows]=useState<any[]>([]),[q,setQ]=useState(""),[modal,setModal]=useState(false),[busy,setBusy]=useState(false);
 async function load(){const {data}=await supabase.from("inventory").select("*,profiles(display_name)").order("created_at",{ascending:false});setRows(data||[])}useEffect(()=>{load()},[]);
 async function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget),file=f.get("photo") as File;const {data:{user}}=await supabase.auth.getUser();if(!user){setBusy(false);return}let photo_path=null;if(file&&file.size){const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_");photo_path=`${user.id}/${crypto.randomUUID()}-${safe}`;const up=await supabase.storage.from("inventory").upload(photo_path,file);if(up.error)photo_path=null}await supabase.from("inventory").insert({title:String(f.get("title")),description:String(f.get("description")||""),owner_id:user.id,photo_path});setBusy(false);setModal(false);load()}
 async function remove(r:any){if(!confirm(`"${r.title}" verwijderen?`))return;if(r.photo_path)await supabase.storage.from("inventory").remove([r.photo_path]);await supabase.from("inventory").delete().eq("id",r.id);load()}
 const shown=rows.filter(r=>`${r.title} ${r.description}`.toLowerCase().includes(q.toLowerCase()));
 return <AppShell><Header title="Inventaris" subtitle="Alles wat bij Rejoice hoort" action={<button className="btn" onClick={()=>setModal(true)}><Plus size={16}/> Item toevoegen</button>}/><div className="card"><div className="toolbar" style={{marginBottom:12}}><div style={{position:"relative",flex:1,maxWidth:360}}><Search size={15} style={{position:"absolute",left:10,top:11,color:"#94a3b8"}}/><input className="input" style={{paddingLeft:32}} placeholder="Zoek in inventaris…" value={q} onChange={e=>setQ(e.target.value)}/></div><span className="badge">{shown.length} items</span></div><div className="grid grid2">{shown.map(r=><div className="card" style={{boxShadow:"none",background:"#fafbfc"}} key={r.id}><div className="toolbar" style={{alignItems:"flex-start"}}>{r.photo_path?<InventoryPhoto path={r.photo_path}/>:<div className="photo" style={{display:"grid",placeItems:"center"}}><PackageOpen size={20}/></div>}<div style={{flex:1}}><div className="row-title">{r.title}</div><div className="row-meta">{r.description||"Geen beschrijving"}</div><div className="row-meta" style={{marginTop:7}}>Eigenaar: {r.profiles?.display_name||"Onbekend"}</div></div><button className="iconbtn" onClick={()=>remove(r)}><Trash2 size={14}/></button></div></div>)}{!shown.length&&<div className="empty">Nog geen inventarisitems.</div>}</div></div>
 {modal&&<Modal title="Inventarisitem toevoegen" onClose={()=>setModal(false)}><form onSubmit={add}><label>Titel *</label><input className="input" name="title" required placeholder="Bijv. Behringer X32"/><label style={{marginTop:13}}>Beschrijving</label><textarea name="description" rows={3} placeholder="Merk, serienummer, waar het ligt…"/><label style={{marginTop:13}}>Foto (optioneel)</label><input className="fileinput" type="file" name="photo" accept="image/*"/><button className="btn" style={{marginTop:15}} disabled={busy}>{busy?"Opslaan…":"Item toevoegen"}</button></form></Modal>}</AppShell>
}
function InventoryPhoto({path}:{path:string}){const [url,setUrl]=useState("");useEffect(()=>{supabase.storage.from("inventory").createSignedUrl(path,3600).then((result)=>setUrl(result.data?.signedUrl||""))},[path]);return url?<img className="photo" src={url} alt=""/>:<div className="photo"/>}
