"use client";
import {useEffect,useMemo,useState} from "react";
import {AppShell} from "@/components/AppShell";import {Header} from "@/components/Header";import {Modal} from "@/components/Modal";import {supabase} from "@/lib/supabase";import {dateTimeNL,googleCalendarUrl} from "@/lib/utils";
import {Plus,ChevronLeft,ChevronRight,Trash2,CalendarPlus} from "lucide-react";

const names=["Zo","Ma","Di","Wo","Do","Vr","Za"];
export default function Agenda(){
 const [events,setEvents]=useState<any[]>([]),[month,setMonth]=useState(new Date()),[modal,setModal]=useState(false),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);const {data}=await supabase.from("calendar_events").select("*").order("starts_at",{ascending:true});setEvents(data||[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 const days=useMemo(()=>{const y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1),start=new Date(y,m,1-first.getDay()),arr=[];for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);arr.push(d)}return arr},[month]);
 async function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const {data:{user}}=await supabase.auth.getUser();if(!user)return;await supabase.from("calendar_events").insert({title:String(f.get("title")),description:String(f.get("description")||""),starts_at:new Date(String(f.get("start"))).toISOString(),ends_at:new Date(String(f.get("end"))).toISOString(),location:String(f.get("location")||""),created_by:user.id});setModal(false);load()}
 async function remove(id:string){if(!confirm("Deze afspraak verwijderen?"))return;await supabase.from("calendar_events").delete().eq("id",id);load()}
 return <AppShell><Header title="Agenda" subtitle="Afspraken en repetities voor de hele band" action={<button className="btn" onClick={()=>setModal(true)}><Plus size={16}/> Nieuwe afspraak</button>}/>
 <div className="card" style={{marginBottom:16}}><div className="toolbar" style={{justifyContent:"space-between"}}><div className="toolbar"><button className="btn secondary small" onClick={()=>setMonth(new Date())}>Vandaag</button><button className="iconbtn" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><ChevronLeft size={17}/></button><button className="iconbtn" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><ChevronRight size={17}/></button><b style={{marginLeft:4}}>{new Intl.DateTimeFormat("nl-NL",{month:"long",year:"numeric"}).format(month)}</b></div><span className="badge">{loading?"laden…":`${events.length} afspraken`}</span></div></div>
 <div className="calendar">{names.map(n=><div className="calhead" key={n}>{n}</div>)}{days.map(d=>{const key=d.toISOString().slice(0,10);const dayEvents=events.filter(e=>e.starts_at.slice(0,10)===key);const today=new Date().toISOString().slice(0,10)===key;return <div className="calcell" key={key}><div className={today?"daynum today":"daynum"}>{d.getDate()}</div>{dayEvents.map(e=><div className="eventdot" title={e.title} key={e.id}>{e.title}</div>)}</div>})}</div>
 <div className="section-title"><h2>Komende afspraken</h2></div><div className="card list">{events.filter(e=>new Date(e.starts_at)>=new Date()).slice(0,12).map(e=><div className="row" key={e.id}><div><div className="row-title">{e.title}</div><div className="row-meta">{dateTimeNL(e.starts_at)}{e.location?` · ${e.location}`:""}</div></div><div className="toolbar"><a className="btn secondary small" target="_blank" href={googleCalendarUrl(e)}><CalendarPlus size={14}/> Google</a><button className="btn danger small" onClick={()=>remove(e.id)}><Trash2 size={14}/></button></div></div>)}{!events.filter(e=>new Date(e.starts_at)>=new Date()).length&&<div className="empty">Geen komende afspraken.</div>}</div>
 {modal&&<Modal title="Nieuwe afspraak" onClose={()=>setModal(false)}><form onSubmit={add}><div className="formgrid"><div className="full"><label>Titel *</label><input className="input" name="title" required placeholder="Repetitie, optreden, vergadering…"/></div><div><label>Start *</label><input className="input" type="datetime-local" name="start" required/></div><div><label>Einde</label><input className="input" type="datetime-local" name="end"/></div><div className="full"><label>Locatie</label><input className="input" name="location"/></div><div className="full"><label>Omschrijving</label><textarea name="description" rows={3}/></div></div><div className="toolbar" style={{marginTop:15}}><button className="btn">Afspraak opslaan</button></div></form></Modal>}
 </AppShell>
}
