"use client";
import {useEffect,useState} from "react";
import {AppShell} from "@/components/AppShell";import {Header} from "@/components/Header";import {Modal} from "@/components/Modal";import {supabase} from "@/lib/supabase";import {dateNL} from "@/lib/utils";import {Upload,Download,Trash2,FileText,Plus} from "lucide-react";
export default function Documenten(){
 const [rows,setRows]=useState<any[]>([]),[modal,setModal]=useState(false),[busy,setBusy]=useState(false),[cat,setCat]=useState("Alles");
 async function load(){const {data}=await supabase.from("documents").select("*").order("created_at",{ascending:false});setRows(data||[])}useEffect(()=>{load()},[]);
 async function upload(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),file=f.get("file") as File;if(!file)return;setBusy(true);const {data:{user}}=await supabase.auth.getUser();if(!user){setBusy(false);return}const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const path=`${user.id}/${crypto.randomUUID()}-${safe}`;const up=await supabase.storage.from("documents").upload(path,file,{upsert:false});if(!up.error)await supabase.from("documents").insert({name:file.name,category:String(f.get("category")||"Overig"),storage_path:path,uploaded_by:user.id});setBusy(false);setModal(false);load()}
 async function download(path:string){const {data,error}=await supabase.storage.from("documents").createSignedUrl(path,60);if(!error&&data?.signedUrl)window.open(data.signedUrl,"_blank")}
 async function remove(r:any){if(confirm(`"${r.name}" verwijderen?`)){await supabase.storage.from("documents").remove([r.storage_path]);await supabase.from("documents").delete().eq("id",r.id);load()}}
 const cats=["Alles",...Array.from(new Set(rows.map(r=>r.category||"Overig")))];const shown=cat==="Alles"?rows:rows.filter(r=>(r.category||"Overig")===cat);
 return <AppShell><Header title="Documenten" subtitle="Bestanden voor de band" action={<button className="btn" onClick={()=>setModal(true)}><Plus size={16}/> Document uploaden</button>}/><div className="card"><div className="tabs" style={{marginBottom:10}}>{cats.map(c=><button key={c} className={cat===c?"tab active":"tab"} onClick={()=>setCat(c)}>{c}</button>)}</div>{shown.map(r=><div className="row" key={r.id}><div className="toolbar"><div style={{width:38,height:38,borderRadius:8,background:"#eff6ff",display:"grid",placeItems:"center"}}><FileText size={18}/></div><div><div className="row-title">{r.name}</div><div className="row-meta">{r.category||"Overig"} · {dateNL(r.created_at)}</div></div></div><div className="toolbar"><button className="btn secondary small" onClick={()=>download(r.storage_path)}><Download size={14}/> Openen</button><button className="btn danger small" onClick={()=>remove(r)}><Trash2 size={14}/></button></div></div>)}{!shown.length&&<div className="empty">Nog geen documenten. Upload bijvoorbeeld een setlist, contract of factuur.</div>}</div>
 {modal&&<Modal title="Document uploaden" onClose={()=>setModal(false)}><form onSubmit={upload}><label>Bestand *</label><input className="fileinput" type="file" name="file" required/><div style={{marginTop:13}}><label>Categorie</label><select className="select" name="category"><option>Overig</option><option>Setlists</option><option>Contracten</option><option>Facturen</option><option>Administratie</option></select></div><button className="btn" style={{marginTop:15}} disabled={busy}>{busy?"Uploaden…":"Uploaden"}</button></form></Modal>}</AppShell>
}
