"use client";
import {useEffect,useMemo,useState} from "react";
import {AppShell} from "@/components/AppShell";import {Header} from "@/components/Header";import {Modal} from "@/components/Modal";import {supabase} from "@/lib/supabase";import {dateNL,euro} from "@/lib/utils";import {Plus,Trash2,Pencil,ArrowDownLeft,ArrowUpRight} from "lucide-react";
export default function Financien(){
 const [rows,setRows]=useState<any[]>([]),[modal,setModal]=useState(false),[edit,setEdit]=useState<any>(null),[filter,setFilter]=useState("all");
 async function load(){const {data}=await supabase.from("finance_transactions").select("*").order("transaction_date",{ascending:false});setRows(data||[])}useEffect(()=>{load()},[]);
 const filtered=rows.filter(r=>filter==="all"||r.type===filter);const income=useMemo(()=>rows.filter(r=>r.type==="income").reduce((n,r)=>n+Number(r.amount),0),[rows]);const expense=useMemo(()=>rows.filter(r=>r.type==="expense").reduce((n,r)=>n+Number(r.amount),0),[rows]);
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const {data:{user}}=await supabase.auth.getUser();if(!user)return;const p={description:String(f.get("description")),amount:Number(f.get("amount")),transaction_date:String(f.get("transaction_date")),category:String(f.get("category")||"Overig"),type:String(f.get("type")),paid_by:edit?.paid_by||user.id,notes:String(f.get("notes")||"")};if(edit)await supabase.from("finance_transactions").update(p).eq("id",edit.id);else await supabase.from("finance_transactions").insert(p);setModal(false);setEdit(null);load()}
 async function remove(id:string){if(confirm("Deze transactie verwijderen?")){await supabase.from("finance_transactions").delete().eq("id",id);load()}}
 return <AppShell><Header title="Financiën" subtitle="Inkomsten, uitgaven en het bandsaldo" action={<button className="btn" onClick={()=>setModal(true)}><Plus size={16}/> Transactie</button>}/><div className="grid grid4"><div className="card stat"><div className="label">Inkomsten</div><div className="value positive">{euro(income)}</div></div><div className="card stat"><div className="label">Uitgaven</div><div className="value negative">{euro(expense)}</div></div><div className="card stat"><div className="label">Saldo</div><div className="value">{euro(income-expense)}</div></div><div className="card stat"><div className="label">Transacties</div><div className="value">{rows.length}</div></div></div><div className="card" style={{marginTop:16}}><div className="toolbar" style={{justifyContent:"space-between",marginBottom:10}}><div className="tabs">{[["all","Alles"],["income","Inkomsten"],["expense","Uitgaven"]].map(([v,l])=><button className={filter===v?"tab active":"tab"} key={v} onClick={()=>setFilter(v)}>{l}</button>)}</div></div><div className="tablewrap"><table className="table"><thead><tr><th>Omschrijving</th><th>Datum</th><th>Categorie</th><th>Bedrag</th><th></th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><b>{r.description}</b></td><td>{dateNL(r.transaction_date)}</td><td>{r.category||"Overig"}</td><td className={r.type==="income"?"positive":"negative"}>{r.type==="income"?"+":"−"} {euro(Number(r.amount))}</td><td><div className="toolbar"><button className="iconbtn" onClick={()=>{setEdit(r);setModal(true)}}><Pencil size={14}/></button><button className="iconbtn" onClick={()=>remove(r.id)}><Trash2 size={14}/></button></div></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">Geen transacties.</div>}</div></div>
 {modal&&<Modal title={edit?"Transactie bewerken":"Nieuwe transactie"} onClose={()=>{setModal(false);setEdit(null)}}><form onSubmit={save}><div className="formgrid"><div><label>Type</label><select className="select" name="type" defaultValue={edit?.type||"income"}><option value="income">Inkomst</option><option value="expense">Uitgave</option></select></div><div><label>Bedrag (€) *</label><input className="input" type="number" step="0.01" name="amount" required defaultValue={edit?.amount}/></div><div><label>Datum *</label><input className="input" type="date" name="transaction_date" required defaultValue={edit?.transaction_date||new Date().toISOString().slice(0,10)}/></div><div><label>Categorie</label><input className="input" name="category" defaultValue={edit?.category}/></div><div className="full"><label>Omschrijving *</label><input className="input" name="description" required defaultValue={edit?.description}/></div><div className="full"><label>Notities</label><textarea name="notes" rows={3} defaultValue={edit?.notes}/></div></div><div className="toolbar" style={{marginTop:15}}><button className="btn">Opslaan</button></div></form></Modal>}</AppShell>
}
