"use client";
import {useEffect,useState} from "react";
import {AppShell} from "@/components/AppShell";import {Header} from "@/components/Header";import {Modal} from "@/components/Modal";import {supabase} from "@/lib/supabase";import {dateNL,euro} from "@/lib/utils";import {Plus,Trash2,Pencil,Search} from "lucide-react";

const statuses=["Optie","Bevestigd","Afgerond","Geannuleerd"];
export default function Boekingen(){
 const [rows,setRows]=useState<any[]>([]),[q,setQ]=useState(""),[modal,setModal]=useState(false),[edit,setEdit]=useState<any>(null);
 async function load(){const {data}=await supabase.from("bookings").select("*").order("event_date",{ascending:true});setRows(data||[])} useEffect(()=>{load()},[]);
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const {data:{user}}=await supabase.auth.getUser();if(!user)return;const payload={title:String(f.get("title")),client_name:String(f.get("client_name")),event_date:String(f.get("event_date")),start_time:f.get("start_time")||null,end_time:f.get("end_time")||null,location:String(f.get("location")||""),fee:Number(f.get("fee")||0),status:String(f.get("status")),notes:String(f.get("notes")||""),created_by:edit?.created_by||user.id}; if(edit)await supabase.from("bookings").update(payload).eq("id",edit.id);else await supabase.from("bookings").insert(payload);setModal(false);setEdit(null);load()}
 async function remove(id:string){if(confirm("Deze boeking verwijderen?")){await supabase.from("bookings").delete().eq("id",id);load()}}
 const filtered=rows.filter(r=>`${r.title} ${r.client_name} ${r.location}`.toLowerCase().includes(q.toLowerCase()));
 return <AppShell><Header title="Boekingen" subtitle="Optredens, aanvragen en opdrachtgevers" action={<button className="btn" onClick={()=>setModal(true)}><Plus size={16}/> Nieuwe boeking</button>}/><div className="card"><div className="toolbar" style={{marginBottom:12}}><div style={{position:"relative",flex:1,maxWidth:360}}><Search size={15} style={{position:"absolute",left:10,top:11,color:"#94a3b8"}}/><input className="input search" style={{paddingLeft:32}} placeholder="Zoek boeking…" value={q} onChange={e=>setQ(e.target.value)}/></div><span className="badge">{filtered.length} resultaten</span></div><div className="tablewrap"><table className="table"><thead><tr><th>Boeking</th><th>Datum</th><th>Locatie</th><th>Bedrag</th><th>Status</th><th></th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><b>{r.title}</b><div className="row-meta">{r.client_name||"—"}</div></td><td>{dateNL(r.event_date)}<div className="row-meta">{r.start_time?.slice(0,5)||""}{r.end_time?` – ${r.end_time.slice(0,5)}`:""}</div></td><td>{r.location||"—"}</td><td>{euro(Number(r.fee))}</td><td><span className={`badge ${r.status==="Bevestigd"?"green":r.status==="Afgerond"?"blue":r.status==="Geannuleerd"?"red":"yellow"}`}>{r.status}</span></td><td><div className="toolbar"><button className="iconbtn" onClick={()=>{setEdit(r);setModal(true)}}><Pencil size={14}/></button><button className="iconbtn" onClick={()=>remove(r.id)}><Trash2 size={14}/></button></div></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">Geen boekingen gevonden.</div>}</div></div>
 {modal&&<Modal title={edit?"Boeking bewerken":"Nieuwe boeking"} onClose={()=>{setModal(false);setEdit(null)}}><form onSubmit={save}><div className="formgrid"><div><label>Titel *</label><input className="input" name="title" required defaultValue={edit?.title}/></div><div><label>Klant / opdrachtgever</label><input className="input" name="client_name" defaultValue={edit?.client_name}/></div><div><label>Datum *</label><input className="input" type="date" name="event_date" required defaultValue={edit?.event_date}/></div><div><label>Status</label><select className="select" name="status" defaultValue={edit?.status||"Optie"}>{statuses.map(s=><option key={s}>{s}</option>)}</select></div><div><label>Starttijd</label><input className="input" type="time" name="start_time" defaultValue={edit?.start_time?.slice(0,5)}/></div><div><label>Eindtijd</label><input className="input" type="time" name="end_time" defaultValue={edit?.end_time?.slice(0,5)}/></div><div><label>Locatie</label><input className="input" name="location" defaultValue={edit?.location}/></div><div><label>Bedrag (€)</label><input className="input" type="number" step="0.01" name="fee" defaultValue={edit?.fee||0}/></div><div className="full"><label>Notities</label><textarea name="notes" rows={3} defaultValue={edit?.notes}/></div></div><div className="toolbar" style={{marginTop:15}}><button className="btn">Opslaan</button></div></form></Modal>}</AppShell>
}
